{
  "artifacts": [
    "resnet50.blacked.json",
    "split_0_accuracy_plot.png",
    "split_0_loss_plot.png",
    "split_0_base_resnet50_fine_tune.h5",
    "resnet50.blacked.link.json"
  ],
  "command": "run",
  "experiment": {
    "base_dir": "/home/steven/github/keras-training-system",
    "dependencies": [
      "importlib==<unknown>",
      "json==2.0.9",
      "keras==2.0.8",
      "numpy==1.13.3",
      "sacred==0.7.1",
      "tensorflow==1.3.1"
    ],
    "mainfile": "run.py",
    "name": "blacked_out_ResNet_50_fine_tuning",
    "repositories": [],
    "sources": [
      [
        "evaluate.py",
        "_sources/evaluate_6b9b8bb899adc5f34d5a55745b09a92b.py"
      ],
      [
        "run.py",
        "_sources/run_e1c94c9c49edca0fc295e4edc99054a5.py"
      ],
      [
        "train.py",
        "_sources/train_fa3e3b9ad61bdbf00ca0277f4e9fe1b3.py"
      ],
      [
        "utils.py",
        "_sources/utils_c98561095e2565dd0b04930ef4a9bd89.py"
      ],
      [
        "writers.py",
        "_sources/writers_083ccd2907821f4f8fcb931422d22bae.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/steven/.conda/envs/py36/lib/python3.6/site-packages/sacred/config/captured_function.py\", line 47, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"run.py\", line 115, in run\n    model = train(model, fine_tuning_config, experiment, training_directory, validation_directory, f'fine_split_{split_index}')\n",
    "  File \"/home/steven/github/keras-training-system/train.py\", line 125, in train\n    callbacks=callbacks)\n",
    "  File \"/home/steven/.conda/envs/py36/lib/python3.6/site-packages/keras/legacy/interfaces.py\", line 87, in wrapper\n    return func(*args, **kwargs)\n",
    "  File \"/home/steven/.conda/envs/py36/lib/python3.6/site-packages/keras/engine/training.py\", line 2042, in fit_generator\n    class_weight=class_weight)\n",
    "  File \"/home/steven/.conda/envs/py36/lib/python3.6/site-packages/keras/engine/training.py\", line 1756, in train_on_batch\n    check_batch_axis=True)\n",
    "  File \"/home/steven/.conda/envs/py36/lib/python3.6/site-packages/keras/engine/training.py\", line 1378, in _standardize_user_data\n    exception_prefix='input')\n",
    "  File \"/home/steven/.conda/envs/py36/lib/python3.6/site-packages/keras/engine/training.py\", line 144, in _standardize_input_data\n    str(array.shape))\n",
    "ValueError: Error when checking input: expected input_1 to have shape (None, 224, 224, 3) but got array with shape (32, 224, 249, 3)\n"
  ],
  "heartbeat": "2018-05-03T22:58:43.335739",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz",
    "gpus": {
      "driver_version": "384.130",
      "gpus": [
        {
          "model": "GeForce GTX 1080 Ti",
          "persistence_mode": false,
          "total_memory": 11163
        }
      ]
    },
    "hostname": "steven",
    "os": [
      "Linux",
      "Linux-4.13.0-39-generic-x86_64-with-debian-stretch-sid"
    ],
    "python_version": "3.6.2"
  },
  "meta": {
    "command": "run",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2018-05-03T22:49:20.688260",
  "status": "FAILED",
  "stop_time": "2018-05-03T22:58:43.336477"
}