{
  "artifacts": [
    "densenet169.imagenet.transfer.medico.json",
    "medico.json",
    "split_0_split_evaluation_summary.txt",
    "split_0_class_misclassifications.txt",
    "split_0_class_results.txt",
    "split_0_test_evaluation_results.txt",
    "split_1_split_evaluation_summary.txt",
    "split_1_class_misclassifications.txt",
    "split_1_class_results.txt",
    "split_1_test_evaluation_results.txt"
  ],
  "command": "wrapper",
  "experiment": {
    "base_dir": "/home/stevenah/github/keras-training-system/src",
    "dependencies": [
      "Keras==2.2.2",
      "numpy==1.14.3",
      "sacred==0.7.4",
      "tensorflow-gpu==1.10.1"
    ],
    "mainfile": "run.py",
    "name": "densenet169_imagenet_transfer_medico",
    "repositories": [],
    "sources": [
      [
        "evaluate.py",
        "_sources/evaluate_8cd8cd34899ba2c51008184886536dec.py"
      ],
      [
        "run.py",
        "_sources/run_6e84f15d7be5fddf96a3233d7c164fdc.py"
      ],
      [
        "train.py",
        "_sources/train_64962813064f77ec594ed8474b3f4258.py"
      ],
      [
        "utils/logging.py",
        "_sources/logging_44c21d0c4e2f675554adcf905290024d.py"
      ],
      [
        "utils/util.py",
        "_sources/util_fd980eab7b859d935486f0fce61a7c2c.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/stevenah/anaconda3/lib/python3.6/site-packages/sacred/config/captured_function.py\", line 46, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"run.py\", line 186, in wrapper\n    run( config, config_path )\n",
    "  File \"run.py\", line 145, in run\n    file_identifier=f'split_{ file_identifier }' )\n",
    "  File \"/home/stevenah/github/keras-training-system/src/evaluate.py\", line 140, in evaluate\n",
    "  File \"/home/stevenah/anaconda3/lib/python3.6/site-packages/numpy/lib/utils.py\", line 101, in newfunc\n    return func(*args, **kwds)\n",
    "  File \"/home/stevenah/anaconda3/lib/python3.6/site-packages/scipy/misc/pilutil.py\", line 555, in imresize\n    im = toimage(arr, mode=mode)\n",
    "  File \"/home/stevenah/anaconda3/lib/python3.6/site-packages/numpy/lib/utils.py\", line 101, in newfunc\n    return func(*args, **kwds)\n",
    "  File \"/home/stevenah/anaconda3/lib/python3.6/site-packages/scipy/misc/pilutil.py\", line 327, in toimage\n    raise ValueError(\"'arr' does not have a suitable array shape for \"\n",
    "ValueError: 'arr' does not have a suitable array shape for any mode.\n"
  ],
  "heartbeat": "2018-09-19T09:15:08.274612",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz",
    "gpus": {
      "driver_version": "390.87",
      "gpus": [
        {
          "model": "GeForce GTX 1080 Ti",
          "persistence_mode": false,
          "total_memory": 11170
        }
      ]
    },
    "hostname": "mpg-2014-12",
    "os": [
      "Linux",
      "Linux-4.15.0-34-generic-x86_64-with-debian-buster-sid"
    ],
    "python_version": "3.6.5"
  },
  "meta": {
    "command": "wrapper",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2018-09-19T08:55:45.926616",
  "status": "FAILED",
  "stop_time": "2018-09-19T09:15:08.275685"
}