{
  "artifacts": [
    "densenet121.imagenet.transfer.medico.json",
    "medico.json"
  ],
  "command": "wrapper",
  "experiment": {
    "base_dir": "/home/stevenah/github/keras-training-system/src",
    "dependencies": [
      "Keras==2.2.2",
      "numpy==1.15.0",
      "sacred==0.7.4",
      "tensorflow-gpu==1.10.1"
    ],
    "mainfile": "run.py",
    "name": "densenet121_imagenet_transfer_medico",
    "repositories": [],
    "sources": [
      [
        "evaluate.py",
        "_sources/evaluate_e66cbd7e9a278546ee8e43552f132bee.py"
      ],
      [
        "run.py",
        "_sources/run_6e84f15d7be5fddf96a3233d7c164fdc.py"
      ],
      [
        "train.py",
        "_sources/train_371ffe8879d615ca7d245fed36d426ed.py"
      ],
      [
        "utils/logging.py",
        "_sources/logging_64e0b2beabe031c84916b52e448659df.py"
      ],
      [
        "utils/util.py",
        "_sources/util_fd980eab7b859d935486f0fce61a7c2c.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/stevenah/anaconda3/lib/python3.6/site-packages/sacred/config/captured_function.py\", line 46, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"run.py\", line 186, in wrapper\n    run( config, config_path )\n",
    "  File \"run.py\", line 112, in run\n    file_identifier=f'split_{ file_identifier }' )\n",
    "  File \"/home/stevenah/github/keras-training-system/src/train.py\", line 182, in train\n    class_weight=class_weigths)\n",
    "  File \"/home/stevenah/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py\", line 91, in wrapper\n    return func(*args, **kwargs)\n",
    "  File \"/home/stevenah/anaconda3/lib/python3.6/site-packages/keras/engine/training.py\", line 1415, in fit_generator\n    initial_epoch=initial_epoch)\n",
    "  File \"/home/stevenah/anaconda3/lib/python3.6/site-packages/keras/engine/training_generator.py\", line 213, in fit_generator\n    class_weight=class_weight)\n",
    "  File \"/home/stevenah/anaconda3/lib/python3.6/site-packages/keras/engine/training.py\", line 1215, in train_on_batch\n    outputs = self.train_function(ins)\n",
    "  File \"/home/stevenah/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py\", line 2666, in __call__\n    return self._call(inputs)\n",
    "  File \"/home/stevenah/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py\", line 2636, in _call\n    fetched = self._callable_fn(*array_vals)\n",
    "  File \"/home/stevenah/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1382, in __call__\n    run_metadata_ptr)\n",
    "  File \"/home/stevenah/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py\", line 519, in __exit__\n    c_api.TF_GetCode(self.status.status))\n",
    "tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,18,18,896] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[Node: training/SGD/gradients/zeros_165-0-1-TransposeNCHWToNHWC-LayoutOptimizer = Transpose[T=DT_FLOAT, Tperm=DT_INT32, _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"](training/SGD/gradients/zeros_165, PermConstNCHWToNHWC-LayoutOptimizer)]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\n\n\t [[Node: loss/add/_5611 = _Recv[client_terminated=false, recv_device=\"/job:localhost/replica:0/task:0/device:CPU:0\", send_device=\"/job:localhost/replica:0/task:0/device:GPU:0\", send_device_incarnation=1, tensor_name=\"edge_31467_loss/add\", tensor_type=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"]()]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\n\n"
  ],
  "heartbeat": "2018-09-25T08:00:25.714350",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz",
    "gpus": {
      "driver_version": "390.87",
      "gpus": [
        {
          "model": "GeForce GTX 1080 Ti",
          "persistence_mode": false,
          "total_memory": 11170
        }
      ]
    },
    "hostname": "mpg-2014-12",
    "os": [
      "Linux",
      "Linux-4.15.0-34-generic-x86_64-with-debian-buster-sid"
    ],
    "python_version": "3.6.5"
  },
  "meta": {
    "command": "wrapper",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2018-09-25T07:59:10.053625",
  "status": "FAILED",
  "stop_time": "2018-09-25T08:00:25.715299"
}