{
  "artifacts": [
    "densenet169.combo.imagenet.transfer.medico.json",
    "medico.json"
  ],
  "command": "wrapper",
  "experiment": {
    "base_dir": "/home/steven/github/keras-training-system/src",
    "dependencies": [
      "Keras==2.2.2",
      "numpy==1.15.1",
      "sacred==0.7.4",
      "tensorflow-gpu==1.10.1"
    ],
    "mainfile": "run.py",
    "name": "densenet169_combo_imagenet_transfer_medico",
    "repositories": [],
    "sources": [
      [
        "evaluate.py",
        "_sources/evaluate_e66cbd7e9a278546ee8e43552f132bee.py"
      ],
      [
        "run.py",
        "_sources/run_6e84f15d7be5fddf96a3233d7c164fdc.py"
      ],
      [
        "train.py",
        "_sources/train_371ffe8879d615ca7d245fed36d426ed.py"
      ],
      [
        "utils/logging.py",
        "_sources/logging_64e0b2beabe031c84916b52e448659df.py"
      ],
      [
        "utils/util.py",
        "_sources/util_fd980eab7b859d935486f0fce61a7c2c.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/steven/anaconda3/envs/keras/lib/python3.6/site-packages/sacred/config/captured_function.py\", line 46, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"run.py\", line 186, in wrapper\n    run( config, config_path )\n",
    "  File \"run.py\", line 97, in run\n    model = model_builder.build(config)\n",
    "  File \"/home/steven/github/keras-training-system/src/models/densenet169_combo.py\", line 13, in build\n    return Model(inputs=models[0].input, outputs=averaged)\n",
    "  File \"/home/steven/anaconda3/envs/keras/lib/python3.6/site-packages/keras/legacy/interfaces.py\", line 91, in wrapper\n    return func(*args, **kwargs)\n",
    "  File \"/home/steven/anaconda3/envs/keras/lib/python3.6/site-packages/keras/engine/network.py\", line 93, in __init__\n    self._init_graph_network(*args, **kwargs)\n",
    "  File \"/home/steven/anaconda3/envs/keras/lib/python3.6/site-packages/keras/engine/network.py\", line 237, in _init_graph_network\n    self.inputs, self.outputs)\n",
    "  File \"/home/steven/anaconda3/envs/keras/lib/python3.6/site-packages/keras/engine/network.py\", line 1430, in _map_graph_network\n    str(layers_with_complete_input))\n",
    "ValueError: Graph disconnected: cannot obtain value for tensor Tensor(\"input_1_2:0\", shape=(?, 299, 299, 3), dtype=float32) at layer \"input_1\". The following previous layers were accessed without issue: []\n"
  ],
  "heartbeat": "2018-09-22T18:37:26.299099",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz",
    "gpus": {
      "driver_version": "384.130",
      "gpus": [
        {
          "model": "GeForce GTX 1080 Ti",
          "persistence_mode": false,
          "total_memory": 11163
        }
      ]
    },
    "hostname": "steven",
    "os": [
      "Linux",
      "Linux-4.15.0-34-generic-x86_64-with-debian-stretch-sid"
    ],
    "python_version": "3.6.6"
  },
  "meta": {
    "command": "wrapper",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2018-09-22T18:35:25.399673",
  "status": "FAILED",
  "stop_time": "2018-09-22T18:37:26.299954"
}